- name: OS Updates (Linux)
  hosts: all
  become: yes
  tasks:
    - name: update using yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: update using apt
      apt:
        name: '*'
        state: latest
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: reboot to complete update
      reboot:
        msg: rebooting to complete Updates
