- name: Search OS Updates (Windows)
  hosts: all
  tasks:
    - name: search windows updates
      win_updates:
        category_names:
          - SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
      register: wu

    - name: summary searched update information
      debug:
        msg: "Found {{ wu.found_update_count }} updates that need to be installed."

    - name: detail searched update information
      debug:
        msg: "{{ item }} - KB{{ wu.updates[item].kb[0] }} - {{ wu.updates[item].title }}" 
      with_items: "{{ wu.updates }}"
