- name: OS Updates (Windows)
  hosts: all
  tasks:
    - name: install windows updates
      win_updates:
        category_names:
          - SecurityUpdates

    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: reboot to complete update
      win_updates:
        reboot: yes
        reboot_timeout: 3600
