- name: OS Updates (Windows)
  hosts: all
  tasks:
    - name: install windows updates
      win_updates:
        category_names:
          - SecurityUpdates

    - name: reboot to complete update
      reboot:
        msg: rebooting to complete Updates
